"""Optional LLM commentary on classification results.

Calls the Anthropic API to produce a plain-English summary of a classification
report and top SHAP drivers. The output is intentionally a *briefing*: short,
non-technical, and explicitly hedged about model limitations.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from cre_stress.config import Settings, get_settings

logger = logging.getLogger(__name__)

PROMPT_TEMPLATE = """\
You are summarizing classification results for a credit-risk analyst on a research
team. Be concise, hedged, and explicit about what the metrics do and do not show.

Model: {model_type}
AUC: {auc:.3f}
Threshold: {threshold:.3f} (chosen so FPR <= {max_fpr:.2f} and recall >= {target_recall:.2f})

Classification report (test set):
{report}

Top SHAP drivers (mean absolute SHAP value, top 5):
{shap_summary}

Write a 4-sentence briefing. Cover (1) what the model classifies, (2) the headline
metrics in plain English, (3) the most important drivers, (4) one explicit caveat
about generalization or label definition.
"""


def summarize_run(
    report: dict,
    auc: float,
    threshold: float,
    top_shap_features: pd.DataFrame | None = None,
    model_type: str = "logistic",
    max_fpr: float = 0.2,
    target_recall: float = 0.8,
    settings: Settings | None = None,
) -> str:
    """Produce a short plain-English summary of one model run.

    Requires ``ANTHROPIC_API_KEY``. The ``anthropic`` SDK is an optional
    dependency — install with ``pip install -e .[commentary]``.
    """
    s = settings or get_settings()
    s.validate_required("anthropic_api_key")

    try:
        from anthropic import Anthropic  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "anthropic SDK not installed. Install with `pip install -e .[commentary]`"
        ) from exc

    shap_summary_str = (
        top_shap_features.to_string(index=False) if top_shap_features is not None else "(unavailable)"
    )
    report_str = pd.DataFrame(report).transpose().round(3).to_string()

    prompt = PROMPT_TEMPLATE.format(
        model_type=model_type,
        auc=auc,
        threshold=threshold,
        max_fpr=max_fpr,
        target_recall=target_recall,
        report=report_str,
        shap_summary=shap_summary_str,
    )

    client = Anthropic(api_key=s.anthropic_api_key)
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=400,
        messages=[{"role": "user", "content": prompt}],
    )
    text = "".join(block.text for block in message.content if getattr(block, "type", None) == "text")
    logger.info("Generated commentary (%d chars)", len(text))
    return text


def write_commentary(text: str, output_path: Path) -> Path:
    """Write commentary to a markdown file. Returns the path written."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"# Run commentary\n\n_Generated by `cre_stress.commentary`._\n\n{text}\n",
        encoding="utf-8",
    )
    return output_path
